export const defaultApplicationIcons = {
    '[dD]iscord': '󰙯',
    '^thunderbird': '',
    'class:wezterm$': '',
    'draw.io': '󰇟',
    'firefox-developer-edition': '',
    'google-chrome': '',
    'title:YouTube ': '',
    Spotify: '󰓇',
    chromium: '',
    brave: '',
    code: '󰨞',
    dbeaver: '',
    edge: '󰇩',
    evince: '',
    firefox: '',
    foot: '',
    keepassxc: '',
    keymapp: '',
    kitty: '',
    ghostty: '',
    obsidian: '󰠮',
    password$: '',
    qBittorrent$: '',
    rofi: '',
    slack: '',
    spotube: '󰓇',
    steam: '',
    telegram: '',
    vlc: '󰕼',
};
